CREATE TABLE IF NOT EXISTS track(
id SERIAL PRIMARY KEY,
singer VARCHAR(300) NOT NULL,
title VARCHAR(300) NOT NULL,
duration INTEGER NOT NULL,
album VARCHAR(300) NOT NULL,
mixtape VARCHAR(300)
);

CREATE TABLE IF NOT EXISTS mixtape (
id SERIAL PRIMARY KEY,
title INTEGER NOT NULL,
release_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS mixtapeTrack(
id SERIAL PRIMARY KEY,
mixtape_id INTEGER NOT NULL REFERENCES mixtape(id) NOT NULL,
track_id INTEGER NOT NULL REFERENCES track(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS album (
id SERIAL PRIMARY KEY,
title VARCHAR(500) NOT NULL,
release_year INTEGER NOT NULL,
singer VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS singer (
id SERIAL PRIMARY KEY,
name VARCHAR(300) NOT NULL,
genre VARCHAR(200) NOT NULL,
album VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS albumSinger (
album_id INTEGER REFERENCES album(id),
singer_id INTEGER REFERENCES singer(id),
CONSTRAINT albsing PRIMARY KEY (album_id, singer_id)
); 

CREATE TABLE IF NOT EXISTS genre (
id SERIAL PRIMARY KEY,
name VARCHAR(200) NOT NULL UNIQUE,
singer VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS singerGenre (
genre_id INTEGER REFERENCES genre(id),
singer_id INTEGER REFERENCES singer(id),
CONSTRAINT singgen PRIMARY KEY (genre_id, singer_id)
);

